# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "composer"
    # Files stored in repository root
    directory: "/app/public/"
    schedule:
      interval: "daily"
      # Check for npm updates at 9am UTC
      time: "09:00"
      # Use Kenya Standard Time (UTC +03:00)
      timezone: "Africa/Nairobi"
    # Add assignees
    assignees:
      - "josephgodwinkimani"    
  - package-ecosystem: "npm"
    # Files stored in `app` directory
    directory: "/frontend/"
    schedule:
      interval: "daily"
      # Check for npm updates at 9am UTC
      time: "09:00"
      # Use Kenya Standard Time (UTC +03:00)
      timezone: "Africa/Nairobi"
    assignees:
      - "josephgodwinkimani"
